name: confirmation_success
description: A Flutter package aim to provide an interactive and visually appealing way to indicate to users that their order/task has been confirmed.
version: 0.0.2
homepage: https://github.com/emantggw/confirmation_success

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
